### ISSUE TITLE
редирект с www на без www и редирект с http на https

### ISSUE THREAD

**Issue by Eldaeron** [rivetweb/bitrix-rodzeta.redirect#10]
При использование 2 редиректов на 1С-Битрикс: Управление сайтом 16.5.6, переходит на защищенное соединение, https://сайт.ру:80 но сайт неоткрываеться

Этот сайт не может обеспечить защищенное соединение

Хост сайт.ру:80 прислал недопустимый ответ.
Проведите диагностику сети Windows.
ERR_SSL_PROTOCOL_ERROR

**Comment by rivetweb** [comment]
примеры ваших данных пришлите

список редиректов

**Comment by Eldaeron** [comment]
Список редиректов пуст.
SSL сертификат куплен и установлен для домена.

**Comment by rivetweb** [comment]
пример урл приведите

откуда редиректит - куда редиректит

**Comment by Eldaeron** [comment]
с http://stepter.net на https://stepter.net

**Comment by rivetweb** [comment]
да баг вроде
еще редиректит с https на https

**Comment by Eldaeron** [comment]
Как пофиксить, есть идеи?

**Comment by rivetweb** [comment]
поправлю конечно
позже

пока просто отключите модуль редиректов через админку

**Comment by Eldaeron** [comment]
отключил

**Comment by rivetweb** [comment]
пофиксил
залил в маркетплейс - модуль переустановить надо (удалить, стереть, потом установить)

**Comment by Eldaeron** [comment]
Неработает всеравно

**Comment by rivetweb** [comment]
проверил - на моем сайте редиректит без проблем.

попробуйте посмотреть какое значение  выдает $_SERVER["HTTPS"] на вашем сервере
скрипт test.php
```
<?php
var_dump($_SERVER["HTTPS"]);

```
текущий протокол  определяется условием
$protocol = !empty($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] != "off" ? "https" : "http";
